# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "上传Fir"
  lane :TestFir do #函数名称，执行打包的时候使用

  scheme_name = "LZRTLSiwftDemo"
  time = Time.new.strftime("%Y%m%d") #获取时间格式
  version = "1.0.0" #获取版本号
  ipaName = "#{scheme_name}_#{version}_#{time}.ipa"
  output_path = "/Users/lijun/Desktop/IPA_Info"

  gym(
      scheme:scheme_name, #项目名称
      export_method:"development",#打包的类型 导出方式 ad-hoc、enterprise、app-store、development
      export_xcargs: "-allowProvisioningUpdates", 
      clean: true, #在构建前先clean
      configuration:"Debug",#模式，默认Release，还有Debug
      output_name:scheme_name,#输出的包名
      output_directory: output_path #输出的位置

    )

    firim(firim_api_token: "1cf61667d1efaa4a1765d66814390db6") # token 在fir 上查看。
  end
end
